### ISSUE TITLE
Susceptibility to Reorg Attacks

### ISSUE THREAD

**Issue by shealtielanz** [shieldify-security/ion-protocol-c7bf309e9dba7e19eb81e456fa4cd3254e5e65b9#1]
## Severity

Low Risk

## Description

Reorg attacks occur most times on L2 chains, and the `VaultFactory` contracts use the non-deterministic `create` method for deploying the `Vault` in the `createVault()` function.

Due to the use of `create` to deploy these contracts, in the case of a reorg event, the addresses will change and users who have used the previous deposits will lose them.

## Location of Affected Code

File: [vault/VaultFactory.sol](https://github.com/Ion-Protocol/ion-protocol/blob/master/src/vault/VaultFactory.sol)
```solidity
function createVault(
        IERC20 baseAsset,
        address feeRecipient,
        uint256 feePercentage,
        string memory name,
        string memory symbol,
        uint48 initialDelay,
        address initialDefaultAdmin,
        bytes32 salt,
        Vault.MarketsArgs memory marketsArgs,
        uint256 initialDeposit
    )
        external
        returns (Vault vault)
    {
        vault = new Vault{ salt: salt }(
            baseAsset, feeRecipient, feePercentage, name, symbol, initialDelay, initialDefaultAdmin, marketsArgs
        );
        
        // code
   }
```

## Recommendation

Consider using `create2` with a non-deterministic `salt + the msg.sender` instead.

## Team Response

N/A

**Comment by shealtielanz** [comment]
Hello @anontheauditor Thanks for the feedback.
I don't see any reason why this should not be deemed of medium severity, based on past reports on this platform and others, also this issue can lead to loss of funds if the users interact with a wrong address.
If I am wrong please enlighten me, else I appeal a higher severity for this finding.
Thanks

**Comment by shealtielanz** [comment]
Hello @ShieldifyMartin thank you for the feedback.
Although I do not understand what you mean by copy pasting, the issue I wrote above directly talks about the factory contract of ION Protocol, If it didn't then can be deemed as nonsensical, which is not the case.
It happens rarely, however the case is when it happens and when it does, it will lead to issues.
Attacks rarely happen point being that it just has to happen once, as far as there is a logical pathway and the scenario can exist I don't see why the rarity of this particular issue makes it of low severity.

**Comment by ShieldifyMartin** [comment]
The finding in its current format is not your finding but a correct one by us. The initial description was about Possum Labs, the description of which was copy paste as well.
